name: nature_dex
description: "자연 도감 NFT 앱"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 화면 이동 관리
  go_router: ^14.0.0
  
  # 상태 관리
  provider: ^6.1.0
  
  # 카메라
  camera: ^0.10.5
  
  # 갤러리에서 사진 선택
  image_picker: ^1.0.7
  
  # 권한 요청
  permission_handler: ^11.0.1
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  
  # 서버 통신
  http: ^1.2.0
  
  # 아이콘
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  #   - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf